import random
import statistics
import csv
import os
from deap import base, creator, tools, algorithms
from engine.contracts import ComponentId
from sim.config import SimulationConfig
from sim.loop import run_simulation
from sim.historian.reader import compare_runs

# Constants from PLAN-B §9.1 (Reduced for demo)
POP_SIZE = 50
N_GEN = 50
LAMBDA_COST = 1.5
LAMBDA_FAILURE = 50.0

# 1. DEAP Setup
if "FitnessMax" not in creator.__dict__:
    creator.create("FitnessMax", base.Fitness, weights=(1.0,))
if "Individual" not in creator.__dict__:
    creator.create("Individual", list, fitness=creator.FitnessMax)

toolbox = base.Toolbox()
toolbox.register("attr_float", random.uniform, 0.1, 0.9)
toolbox.register("individual", tools.initRepeat, creator.Individual, toolbox.attr_float, n=7)
toolbox.register("population", tools.initRepeat, list, toolbox.individual)

def fitness(individual):
    """Fitness function as defined in §9.2."""
    thresholds = {
        ComponentId.BLADE: individual[0],
        ComponentId.MOTOR: individual[1],
        ComponentId.NOZZLE: individual[2],
        ComponentId.RESISTOR: individual[3],
        ComponentId.HEATER: individual[4],
        ComponentId.INSULATION: individual[5]
    }
    lookahead = individual[6]
    
    cfg = SimulationConfig(
        scenario_name="stressed",
        policy="ai",
        seed=42,
        config_json={"thresholds": thresholds, "lookahead": lookahead},
        historian_path="ga_tmp.db"
    )
    
    # Run simulation
    run_id = run_simulation(cfg)
    
    # Compute metrics
    metrics = compare_runs([run_id], "uptime_hours", db_path="ga_tmp.db")
    uptime = metrics[run_id]
    
    maintenance_count = compare_runs([run_id], "maintenance_count", db_path="ga_tmp.db")[run_id]
    catastrophic_failures = compare_runs([run_id], "failure_count", db_path="ga_tmp.db")[run_id]
    return (uptime - LAMBDA_COST * maintenance_count - LAMBDA_FAILURE * catastrophic_failures,)

toolbox.register("evaluate", fitness)
toolbox.register("mate", tools.cxBlend, alpha=0.5)
toolbox.register("mutate", tools.mutGaussian, mu=0, sigma=0.05, indpb=0.2)
toolbox.register("select", tools.selTournament, tournsize=3)

def run_ga():
    """Main GA loop as defined in §9."""
    pop = toolbox.population(n=POP_SIZE)
    
    # Log to CSV §9.4
    csv_path = "data/ga_fitness.csv"
    os.makedirs("data", exist_ok=True)
    
    with open(csv_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["generation", "best_fitness", "mean_fitness", "std_fitness"])
        writer.writeheader()
        
        for gen in range(N_GEN):
            offspring = algorithms.varAnd(pop, toolbox, cxpb=0.5, mutpb=0.2)
            fits = toolbox.map(toolbox.evaluate, offspring)
            for ind, fit in zip(offspring, fits):
                ind.fitness.values = fit
            pop = toolbox.select(offspring, k=len(pop))
            
            # Logging
            fitnesses = [ind.fitness.values[0] for ind in pop]
            writer.writerow({
                "generation": gen,
                "best_fitness": max(fitnesses),
                "mean_fitness": statistics.mean(fitnesses),
                "std_fitness": statistics.stdev(fitnesses) if len(fitnesses) > 1 else 0.0
            })
            print(f"Gen {gen}: Best = {max(fitnesses):.4f}")

    # Save final winner to config/policies.yaml §9.5
    best_ind = tools.selBest(pop, 1)[0]
    os.makedirs("config", exist_ok=True)
    with open("config/policies.yaml", "w") as f:
        f.write("# Generated by GA\n")
        f.write("ai_policy:\n")
        f.write("  thresholds:\n")
        for i, cid in enumerate([ComponentId.BLADE, ComponentId.MOTOR, ComponentId.NOZZLE, ComponentId.RESISTOR, ComponentId.HEATER, ComponentId.INSULATION]):
            f.write(f"    {cid.value}: {best_ind[i]:.4f}\n")
        f.write(f"  lookahead_coef: {best_ind[6]:.4f}\n")

if __name__ == "__main__":
    run_ga()
